[package]
name = "dfs_bfs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
graph = { path = "../graph" }
fnv = "1.0.7"
